version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"
    depends_on:
      - backend
      - frontend
    
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production-backend
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
      - TMDB_API_KEY=${TMDB_API_KEY}
    depends_on:
      - redis
  
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production-frontend
    environment:
      - NODE_ENV=production
      - PORT=8080
      - ORIGIN=http://web

