version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production-backend
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
      - TMDB_API_KEY=${TMDB_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - redis
  
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production-frontend
    environment:
      - NODE_ENV=production
      - PORT=8080
      # - ORIGIN=http://test.localhost.com
    ports:
      - "8080:8080"

